Modulo3/Back-end/dotnet/AgenciaViagem/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using dotnet.Data;
using dotnet.Models;

namespace dotnet.Controllers
{
    public class ClienteController : Controller
    {
        private readonly DBContext _context;

        public ClienteController(DBContext context)
        {
            _context = context;
        }

        // GET: Cliente
        public async Task<IActionResult> Index()
        {
            return View(await _context.Cliente.ToListAsync());
        }

        // GET: Cliente/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Cliente
                .FirstOrDefaultAsync(m => m.ID_Cliente == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // GET: Cliente/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cliente/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID_Cliente,Nome,Cpf,Telefone")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Cliente/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Cliente.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        // POST: Cliente/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID_Cliente,Nome,Cpf,Telefone")] Cliente cliente)
        {
            if (id != cliente.ID_Cliente)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.ID_Cliente))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Cliente/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Cliente
                .FirstOrDefaultAsync(m => m.ID_Cliente == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Cliente/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cliente = await _context.Cliente.FindAsync(id);
            _context.Cliente.Remove(cliente);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClienteExists(int id)
        {
            return _context.Cliente.Any(e => e.ID_Cliente == id);
        }
    }
}

Modulo3/Back-end/dotnet/AgenciaViagem/Controllers/FazController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using dotnet.Data;
using dotnet.Models;

namespace dotnet.Controllers
{
    public class FazController : Controller
    {
        private readonly DBContext _context;

        public FazController(DBContext context)
        {
            _context = context;
        }

        // GET: Faz
        public async Task<IActionResult> Index()
        {
            var dBContext = _context.Faz.Include(f => f.cliente).Include(f => f.viagem);
            return View(await dBContext.ToListAsync());
        }

        // GET: Faz/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var faz = await _context.Faz
                .Include(f => f.cliente)
                .Include(f => f.viagem)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (faz == null)
            {
                return NotFound();
            }

            return View(faz);
        }

        // GET: Faz/Create
        public IActionResult Create()
        {
            ViewData["ClienteID_Cliente"] = new SelectList(_context.Cliente, "ID_Cliente", "Cpf");
            ViewData["ViagemID_Viagem"] = new SelectList(_context.Viagem, "ID_Viagem", "Destino");
            return View();
        }

        // POST: Faz/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ClienteID_Cliente,ViagemID_Viagem")] Faz faz)
        {
            if (ModelState.IsValid)
            {
                _context.Add(faz);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteID_Cliente"] = new SelectList(_context.Cliente, "ID_Cliente", "Cpf", faz.ClienteID_Cliente);
            ViewData["ViagemID_Viagem"] = new SelectList(_context.Viagem, "ID_Viagem", "Destino", faz.ViagemID_Viagem);
            return View(faz);
        }

        // GET: Faz/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var faz = await _context.Faz.FindAsync(id);
            if (faz == null)
            {
                return NotFound();
            }
            ViewData["ClienteID_Cliente"] = new SelectList(_context.Cliente, "ID_Cliente", "Cpf", faz.ClienteID_Cliente);
            ViewData["ViagemID_Viagem"] = new SelectList(_context.Viagem, "ID_Viagem", "Destino", faz.ViagemID_Viagem);
            return View(faz);
        }

        // POST: Faz/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ClienteID_Cliente,ViagemID_Viagem")] Faz faz)
        {
            if (id != faz.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(faz);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FazExists(faz.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteID_Cliente"] = new SelectList(_context.Cliente, "ID_Cliente", "Cpf", faz.ClienteID_Cliente);
            ViewData["ViagemID_Viagem"] = new SelectList(_context.Viagem, "ID_Viagem", "Destino", faz.ViagemID_Viagem);
            return View(faz);
        }

        // GET: Faz/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var faz = await _context.Faz
                .Include(f => f.cliente)
                .Include(f => f.viagem)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (faz == null)
            {
                return NotFound();
            }

            return View(faz);
        }

        // POST: Faz/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var faz = await _context.Faz.FindAsync(id);
            _context.Faz.Remove(faz);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FazExists(int id)
        {
            return _context.Faz.Any(e => e.Id == id);
        }
    }
}

Modulo3/Back-end/dotnet/AgenciaViagem/Controllers/ViagemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using dotnet.Data;
using dotnet.Models;

namespace dotnet.Controllers
{
    public class ViagemController : Controller
    {
        private readonly DBContext _context;

        public ViagemController(DBContext context)
        {
            _context = context;
        }

        // GET: Viagem
        public async Task<IActionResult> Index()
        {
            return View(await _context.Viagem.ToListAsync());
        }

        // GET: Viagem/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viagem = await _context.Viagem
                .FirstOrDefaultAsync(m => m.ID_Viagem == id);
            if (viagem == null)
            {
                return NotFound();
            }

            return View(viagem);
        }

        // GET: Viagem/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Viagem/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID_Viagem,Partida,Destino,Origem")] Viagem viagem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(viagem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(viagem);
        }

        // GET: Viagem/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viagem = await _context.Viagem.FindAsync(id);
            if (viagem == null)
            {
                return NotFound();
            }
            return View(viagem);
        }

        // POST: Viagem/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID_Viagem,Partida,Destino,Origem")] Viagem viagem)
        {
            if (id != viagem.ID_Viagem)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(viagem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ViagemExists(viagem.ID_Viagem))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(viagem);
        }

        // GET: Viagem/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viagem = await _context.Viagem
                .FirstOrDefaultAsync(m => m.ID_Viagem == id);
            if (viagem == null)
            {
                return NotFound();
            }

            return View(viagem);
        }

        // POST: Viagem/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var viagem = await _context.Viagem.FindAsync(id);
            _context.Viagem.Remove(viagem);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ViagemExists(int id)
        {
            return _context.Viagem.Any(e => e.ID_Viagem == id);
        }
    }
}

Modulo3/Back-end/dotnet/AgenciaViagem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AgenciaViagem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header class="bg-dark">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark mx-auto">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img class="logo" height="140" src="~/img/logo2.png" alt="logo" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="#navbarColor01"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse fix-mobil" id="navbarColor01">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Destinos">Destinos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Promocoes">Promoções</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Contato">Contato</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Cliente" asp-action="Index">Cliente</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Viagem" asp-action="Index">Viagem</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Faz" asp-action="Index">Passagem</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="d-flex flex-wrap bg-dark justify-content-center aligne-items-center">
        <div class="item">
            <img src="~/img/logo2.png" height="140" alt="logo" />
        </div>
        <div class="item">
            <h3>Inicio</h3>
            <a href="/" style="display: block; font-size: 1.4rem; color: #ccc;">Home</a>
            <a asp-area="" asp-controller="Home" asp-action="Destinos" style="display: block; font-size: 1.4rem; color: #ccc;">Destinos</a>
            <a href="Promocoes" style="display: block; font-size: 1.4rem; color: #ccc;">Promoções</a>
        </div>
        <div class="item">
            <h3>Empresa</h3>
            <a href="#" style="display: block; font-size: 1.4rem; color: #ccc;">Empresa</a>
            <a href="#" style="display: block; font-size: 1.4rem; color: #ccc;">Contato</a>
            <a href="#" style="display: block; font-size: 1.4rem; color: #ccc;">Blog</a>
        </div>
        <div class="item">
            <h3>Suporte</h3>
            <a href="#" style="display: block; font-size: 1.4rem; color: #ccc;">FAQ</a>
            <a href="#" style="display: block; font-size: 1.4rem; color: #ccc;">Telefones</a>
            <a href="#" style="display: block; font-size: 1.4rem; color: #ccc;">Chat</a>
        </div>
        <div class="item">
            <h3>Redes Sociais</h3>
            <a href="https://pt-br.facebook.com" class="fa fa-facebook"></a>
            <a href="https://twitter.com" class="fa fa-twitter"></a>
            <a href="https://www.instagram.com" class="fa fa-instagram"></a>
            
            <a href="https://br.linkedin.com/" class="fa fa-linkedin"></a>
            <a href="https://www.youtube.com/" class="fa fa-youtube"></a>
        </div>
    </footer>
    <div class="copy">
        &copy; 2022 Copyright - Monteiro Viagens
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>